include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false  # 允许在测试和调试脚本中使用 print

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "scripts/**"
    - "mcp_server/**"
  
  errors:
    deprecated_member_use: ignore  # 忽略 withOpacity 等已弃用但仍可用的 API
