// Generated file - do not edit manually

const Map<String, Map<String, dynamic>> abilityDetailsData = {
  'stench': {
    'name': '恶臭',
    'description': '通过释放臭臭的气味，在攻击的时候，有时会使对手畏缩。',
  },
  'drizzle': {
    'name': '降雨',
    'description': '出场时，会将天气变为下雨。',
  },
  'speed-boost': {
    'name': '加速',
    'description': '每一回合速度会变快。',
  },
  'battle-armor': {
    'name': '战斗盔甲',
    'description': '被坚硬的甲壳守护着，不会被对手的攻击击中要害。',
  },
  'sturdy': {
    'name': '结实',
    'description': '在ＨＰ全满时，即使受到招式攻击，也不会被一击打倒。一击必杀的招式也没有效果。',
  },
  'damp': {
    'name': '湿气',
    'description': '通过把周围都弄湿，使谁都无法使用自爆等爆炸类的招式。',
  },
  'limber': {
    'name': '柔软',
    'description': '因为身体柔软，不会变为麻痹状态。',
  },
  'sand-veil': {
    'name': '沙隐',
    'description': '在沙暴的时候，闪避率会提高。',
  },
  'static': {
    'name': '静电',
    'description': '身上带有静电，有时会让接触到的对手麻痹。',
  },
  'volt-absorb': {
    'name': '蓄电',
    'description': '受到电属性的招式攻击时，不会受到伤害，而是会回复。',
  },
  'water-absorb': {
    'name': '储水',
    'description': '受到水属性的招式攻击时，不会受到伤害，而是会回复。',
  },
  'oblivious': {
    'name': '迟钝',
    'description': '因为感觉迟钝，不会变为着迷和被挑衅状态。对威吓也毫不动摇。',
  },
  'cloud-nine': {
    'name': '无关天气',
    'description': '任何天气的影响都会消失。',
  },
  'compound-eyes': {
    'name': '复眼',
    'description': '因为拥有复眼，招式的命中率会提高。',
  },
  'insomnia': {
    'name': '不眠',
    'description': '因为有着睡不着的体质，所以不会陷入睡眠状态。',
  },
  'color-change': {
    'name': '变色',
    'description': '自己的属性会变为从对手处所受招式的属性。',
  },
  'immunity': {
    'name': '免疫',
    'description': '因为体内拥有免疫能力，不会变为中毒状态。',
  },
  'flash-fire': {
    'name': '引火',
    'description': '受到火属性的招式攻击时，吸收火焰，自己使出的火属性招式会变强。',
  },
  'shield-dust': {
    'name': '鳞粉',
    'description': '被鳞粉守护着，不会受到招式的追加效果影响。',
  },
  'own-tempo': {
    'name': '我行我素',
    'description': '因为我行我素，不会变为混乱状态。对威吓也毫不动摇。',
  },
  'suction-cups': {
    'name': '吸盘',
    'description': '用吸盘牢牢贴在地面上，让替换宝可梦的招式和道具无效。',
  },
  'intimidate': {
    'name': '威吓',
    'description': '出场时威吓对手，让其退缩，降低对手的攻击。',
  },
  'shadow-tag': {
    'name': '踩影',
    'description': '踩住对手的影子使其无法逃走或替换。',
  },
  'rough-skin': {
    'name': '粗糙皮肤',
    'description': '受到攻击时，用粗糙的皮肤弄伤接触到自己的对手。',
  },
  'wonder-guard': {
    'name': '神奇守护',
    'description': '不可思议的力量，只有效果绝佳的招式才能击中。',
  },
  'levitate': {
    'name': '飘浮',
    'description': '从地面浮起，从而不会受到地面属性招式的攻击。',
  },
  'effect-spore': {
    'name': '孢子',
    'description': '受到攻击时，有时会把接触到自己的对手变为中毒、麻痹或睡眠状态。',
  },
  'synchronize': {
    'name': '同步',
    'description': '将自己的中毒、麻痹或灼伤状态传染给对手。',
  },
  'clear-body': {
    'name': '恒净之躯',
    'description': '不会因为对手的招式或特性而被降低能力。',
  },
  'natural-cure': {
    'name': '自然回复',
    'description': '回到同行队伍后，异常状态就会被治愈。',
  },
  'lightning-rod': {
    'name': '避雷针',
    'description': '将电属性的招式吸引到自己身上，不会受到伤害，而是会提高特攻。',
  },
  'serene-grace': {
    'name': '天恩',
    'description': '托天恩的福，招式的追加效果容易出现。',
  },
  'swift-swim': {
    'name': '悠游自如',
    'description': '下雨天气时，速度会提高。',
  },
  'chlorophyll': {
    'name': '叶绿素',
    'description': '晴朗天气时，速度会提高。',
  },
  'illuminate': {
    'name': '发光',
    'description': '通过让周围变亮来保持命中率不会被降低。',
  },
  'trace': {
    'name': '复制',
    'description': '出场时，复制对手的特性，变为与之相同的特性。',
  },
  'huge-power': {
    'name': '大力士',
    'description': '物理攻击的威力会变为２倍。',
  },
  'poison-point': {
    'name': '毒刺',
    'description': '有时会让接触到自己的对手变为中毒状态。',
  },
  'inner-focus': {
    'name': '精神力',
    'description': '拥有经过锻炼的精神，而不会因对手的攻击而畏缩。对威吓也毫不动摇。',
  },
  'magma-armor': {
    'name': '熔岩铠甲',
    'description': '将炽热的熔岩覆盖在身上，不会变为冰冻状态。',
  },
  'water-veil': {
    'name': '水幕',
    'description': '将水幕裹在身上，不会变为灼伤状态。',
  },
  'magnet-pull': {
    'name': '磁力',
    'description': '用磁力吸住钢属性的宝可梦，使其无法逃走。',
  },
  'soundproof': {
    'name': '隔音',
    'description': '通过屏蔽声音，不受到声音招式的影响。',
  },
  'rain-dish': {
    'name': '雨盘',
    'description': '下雨天气时，会缓缓回复ＨＰ。',
  },
  'sand-stream': {
    'name': '扬沙',
    'description': '出场时，会把天气变为沙暴。',
  },
  'pressure': {
    'name': '压迫感',
    'description': '给予对手压迫感，大量减少其使用招式的ＰＰ。',
  },
  'thick-fat': {
    'name': '厚脂肪',
    'description': '因为被厚厚的脂肪保护着，会让火属性和冰属性的招式伤害减半。',
  },
  'early-bird': {
    'name': '早起',
    'description': '即使变为睡眠状态，也能以２倍的速度提早醒来。',
  },
  'flame-body': {
    'name': '火焰之躯',
    'description': '有时会让接触到自己的对手变为灼伤状态。',
  },
  'run-away': {
    'name': '逃跑',
    'description': '一定能从野生宝可梦那儿逃走。',
  },
  'keen-eye': {
    'name': '锐利目光',
    'description': '多亏了锐利的目光，命中率不会被降低。',
  },
  'hyper-cutter': {
    'name': '怪力钳',
    'description': '因为拥有以力量自豪的钳子，不会被对手降低攻击。',
  },
  'pickup': {
    'name': '捡拾',
    'description': '有时会捡来对手用过的道具，冒险过程中也会捡到。',
  },
  'truant': {
    'name': '懒惰',
    'description': '如果使出招式，下一回合就会休息。',
  },
  'hustle': {
    'name': '活力',
    'description': '自己的攻击变高，但命中率会降低。',
  },
  'cute-charm': {
    'name': '迷人之躯',
    'description': '有时会让接触到自己的对手着迷。',
  },
  'plus': {
    'name': '正电',
    'description': '出场的伙伴之间如果有正电或负电特性的宝可梦，自己的特攻会提高。',
  },
  'minus': {
    'name': '负电',
    'description': '出场的伙伴之间如果有正电或负电特性的宝可梦，自己的特攻会提高。',
  },
  'forecast': {
    'name': '阴晴不定',
    'description': '受天气的影响，会变为水属性、火属性或冰属性中的某一个。',
  },
  'sticky-hold': {
    'name': '黏着',
    'description': '因为道具是粘在黏性身体上的，所以不会被对手夺走。',
  },
  'shed-skin': {
    'name': '蜕皮',
    'description': '通过蜕去身上的皮，有时会治愈异常状态。',
  },
  'guts': {
    'name': '毅力',
    'description': '如果变为异常状态，会拿出毅力，攻击会提高。',
  },
  'marvel-scale': {
    'name': '神奇鳞片',
    'description': '如果变为异常状态，神奇鳞片会发生反应，防御会提高。',
  },
  'liquid-ooze': {
    'name': '污泥浆',
    'description': '吸收了污泥浆的对手会因强烈的恶臭而受到伤害，减少ＨＰ。',
  },
  'overgrow': {
    'name': '茂盛',
    'description': 'ＨＰ减少的时候，草属性的招式威力会提高。',
  },
  'blaze': {
    'name': '猛火',
    'description': 'ＨＰ减少的时候，火属性的招式威力会提高。',
  },
  'torrent': {
    'name': '激流',
    'description': 'ＨＰ减少的时候，水属性的招式威力会提高。',
  },
  'swarm': {
    'name': '虫之预感',
    'description': 'ＨＰ减少的时候，虫属性的招式威力会提高。',
  },
  'rock-head': {
    'name': '坚硬脑袋',
    'description': '即使使出会受反作用力伤害的招式，ＨＰ也不会减少。',
  },
  'drought': {
    'name': '日照',
    'description': '出场时，会将天气变为晴朗。',
  },
  'arena-trap': {
    'name': '沙穴',
    'description': '在战斗中让对手无法逃走。',
  },
  'vital-spirit': {
    'name': '干劲',
    'description': '通过激发出干劲，不会变为睡眠状态。',
  },
  'white-smoke': {
    'name': '白色烟雾',
    'description': '被白色烟雾保护着，不会被对手降低能力。',
  },
  'pure-power': {
    'name': '瑜伽之力',
    'description': '因瑜伽的力量，物理攻击的威力会变为２倍。',
  },
  'shell-armor': {
    'name': '硬壳盔甲',
    'description': '被坚硬的壳保护着，对手的攻击不会击中要害。',
  },
  'cacophony': {
    'name': '杂音',
    'description': '不受到声音招式的影响。',
  },
  'air-lock': {
    'name': '气闸',
    'description': '所有天气的影响都会消失。',
  },
  'tangled-feet': {
    'name': '蹒跚',
    'description': '在混乱状态时，闪避率会提高。',
  },
  'motor-drive': {
    'name': '电气引擎',
    'description': '受到电属性的招式攻击时，不会受到伤害，而是速度会提高。',
  },
  'rivalry': {
    'name': '斗争心',
    'description': '面对性别相同的对手，会燃起斗争心，变得更强。而面对性别不同的，则会变弱。',
  },
  'steadfast': {
    'name': '不屈之心',
    'description': '每次畏缩时，不屈之心就会燃起，速度也会提高。',
  },
  'snow-cloak': {
    'name': '雪隐',
    'description': '下雪天气时，闪避率会提高。',
  },
  'gluttony': {
    'name': '贪吃鬼',
    'description': '原本ＨＰ变得很少时才会吃树果，在ＨＰ还有一半时就会把它吃掉。',
  },
  'anger-point': {
    'name': '愤怒穴位',
    'description': '要害被击中时，会大发雷霆，攻击力变为最大。',
  },
  'unburden': {
    'name': '轻装',
    'description': '失去所持有的道具时，速度会提高。',
  },
  'heatproof': {
    'name': '耐热',
    'description': '耐热的体质会让火属性的招式伤害减半。',
  },
  'simple': {
    'name': '单纯',
    'description': '能力变化会变为平时的２倍。',
  },
  'dry-skin': {
    'name': '干燥皮肤',
    'description': '下雨天气时和受到水属性的招式时，ＨＰ会回复。晴朗天气时和受到火属性的招式时，ＨＰ会减少。',
  },
  'download': {
    'name': '下载',
    'description': '比较对手的防御和特防，根据较低的那项能力相应地提高自己的攻击或特攻。',
  },
  'iron-fist': {
    'name': '铁拳',
    'description': '使用拳类招式的威力会提高。',
  },
  'poison-heal': {
    'name': '毒疗',
    'description': '变为中毒状态时，ＨＰ不会减少，反而会增加起来。',
  },
  'adaptability': {
    'name': '适应力',
    'description': '与自身同属性的招式威力会提高。',
  },
  'skill-link': {
    'name': '连续攻击',
    'description': '如果使用连续招式，总是能使出最高次数。',
  },
  'hydration': {
    'name': '湿润之躯',
    'description': '下雨天气时，异常状态会治愈。',
  },
  'solar-power': {
    'name': '太阳之力',
    'description': '晴朗天气时，特攻会提高，而每回合ＨＰ会减少。',
  },
  'quick-feet': {
    'name': '飞毛腿',
    'description': '变为异常状态时，速度会提高。',
  },
  'normalize': {
    'name': '一般皮肤',
    'description': '无论是什么属性的招式，全部会变为一般属性。威力会少量提高。',
  },
  'sniper': {
    'name': '狙击手',
    'description': '击中要害时，威力会变得更强。',
  },
  'magic-guard': {
    'name': '魔法防守',
    'description': '不会受到攻击以外的伤害。',
  },
  'no-guard': {
    'name': '无防守',
    'description': '由于无防守战术，双方使出的招式都必定会击中。',
  },
  'stall': {
    'name': '慢出',
    'description': '使出招式的顺序必定会变为最后。',
  },
  'technician': {
    'name': '技术高手',
    'description': '攻击时可以将低威力招式的威力提高。',
  },
  'leaf-guard': {
    'name': '叶子防守',
    'description': '晴朗天气时，不会变为异常状态。',
  },
  'klutz': {
    'name': '笨拙',
    'description': '无法使用持有的道具。',
  },
  'mold-breaker': {
    'name': '破格',
    'description': '可以不受对手特性的干扰，向对手使出招式。',
  },
  'super-luck': {
    'name': '超幸运',
    'description': '因为拥有超幸运，攻击容易击中对手的要害。',
  },
  'aftermath': {
    'name': '引爆',
    'description': '变为濒死时，会对接触到自己的对手造成伤害。',
  },
  'anticipation': {
    'name': '危险预知',
    'description': '可以察觉到对手拥有的危险招式。',
  },
  'forewarn': {
    'name': '预知梦',
    'description': '出场时，只读取１个对手拥有的招式。',
  },
  'unaware': {
    'name': '纯朴',
    'description': '可以无视对手能力的变化，进行攻击。',
  },
  'tinted-lens': {
    'name': '有色眼镜',
    'description': '可以将效果不好的招式以通常的威力使出。',
  },
  'filter': {
    'name': '过滤',
    'description': '受到效果绝佳的攻击时，可以减弱其威力。',
  },
  'slow-start': {
    'name': '慢启动',
    'description': '在５回合内，攻击和速度减半。',
  },
  'scrappy': {
    'name': '胆量',
    'description': '一般属性和格斗属性的招式可以击中幽灵属性的宝可梦。对威吓也毫不动摇。',
  },
  'storm-drain': {
    'name': '引水',
    'description': '将水属性的招式引到自己身上，不会受到伤害，而是会提高特攻。',
  },
  'ice-body': {
    'name': '冰冻之躯',
    'description': '下雪天气时，会缓缓回复ＨＰ。',
  },
  'solid-rock': {
    'name': '坚硬岩石',
    'description': '受到效果绝佳的攻击时，可以减弱其威力。',
  },
  'snow-warning': {
    'name': '降雪',
    'description': '出场时，会将天气变为下雪。',
  },
  'honey-gather': {
    'name': '采蜜',
    'description': '战斗结束时，有时候会捡来甜甜蜜。',
  },
  'frisk': {
    'name': '察觉',
    'description': '出场时，可以察觉对手的持有物。',
  },
  'reckless': {
    'name': '舍身',
    'description': '自己会因反作用力受伤的招式，其威力会提高。',
  },
  'multitype': {
    'name': '多属性',
    'description': '自己的属性会根据持有的石板而改变。',
  },
  'flower-gift': {
    'name': '花之礼',
    'description': '晴朗天气时，自己与同伴的攻击和特防能力会提高。',
  },
  'bad-dreams': {
    'name': '梦魇',
    'description': '给予睡眠状态的对手伤害。',
  },
  'pickpocket': {
    'name': '顺手牵羊',
    'description': '盗取接触到自己的对手的道具。',
  },
  'sheer-force': {
    'name': '强行',
    'description': '招式的追加效果消失，但因此能以更高的威力使出招式。',
  },
  'contrary': {
    'name': '唱反调',
    'description': '能力的变化发生逆转，原本提高时会降低，而原本降低时会提高。',
  },
  'unnerve': {
    'name': '紧张感',
    'description': '让对手紧张，使其无法食用树果。',
  },
  'defiant': {
    'name': '不服输',
    'description': '被对手降低能力时，攻击会大幅提高。',
  },
  'defeatist': {
    'name': '软弱',
    'description': 'ＨＰ减半时，会变得软弱，攻击和特攻会减半。',
  },
  'cursed-body': {
    'name': '咒术之躯',
    'description': '受到攻击时，有时会把对手的招式变为定身法状态。',
  },
  'healer': {
    'name': '治愈之心',
    'description': '有时会治愈异常状态的同伴。',
  },
  'friend-guard': {
    'name': '友情防守',
    'description': '可以减少我方的伤害。',
  },
  'weak-armor': {
    'name': '碎裂铠甲',
    'description': '受到物理招式的伤害时，防御会降低，速度会大幅提高。',
  },
  'heavy-metal': {
    'name': '重金属',
    'description': '自身的重量会变为２倍。',
  },
  'light-metal': {
    'name': '轻金属',
    'description': '自身的重量会减半。',
  },
  'multiscale': {
    'name': '多重鳞片',
    'description': 'ＨＰ全满时，受到的伤害会变少。',
  },
  'toxic-boost': {
    'name': '中毒激升',
    'description': '变为中毒状态时，物理招式的威力会提高。',
  },
  'flare-boost': {
    'name': '受热激升',
    'description': '变为灼伤状态时，特殊招式的威力会提高。',
  },
  'harvest': {
    'name': '收获',
    'description': '可以多次制作出已被使用掉的树果。',
  },
  'telepathy': {
    'name': '心灵感应',
    'description': '读取我方的攻击，并闪避其招式伤害。',
  },
  'moody': {
    'name': '心情不定',
    'description': '每一回合，能力中的某项会大幅提高，而某项会降低。',
  },
  'overcoat': {
    'name': '防尘',
    'description': '不会受到沙暴的伤害。也不会受到粉末类和孢子类招式的影响。',
  },
  'poison-touch': {
    'name': '毒手',
    'description': '只通过接触就有可能让对手变为中毒状态。',
  },
  'regenerator': {
    'name': '再生力',
    'description': '退回同行队伍后，ＨＰ会少量回复。',
  },
  'big-pecks': {
    'name': '健壮胸肌',
    'description': '不会受到防御降低的效果。',
  },
  'sand-rush': {
    'name': '拨沙',
    'description': '沙暴天气时，速度会提高。',
  },
  'wonder-skin': {
    'name': '奇迹皮肤',
    'description': '成为不易受到变化招式攻击的身体。',
  },
  'analytic': {
    'name': '分析',
    'description': '如果在最后使出招式，招式的威力会提高。',
  },
  'illusion': {
    'name': '幻觉',
    'description': '假扮成同行队伍中的最后一只宝可梦出场，迷惑对手。',
  },
  'imposter': {
    'name': '变身者',
    'description': '变身为当前面对的宝可梦。',
  },
  'infiltrator': {
    'name': '穿透',
    'description': '可以穿透对手的壁障或替身进行攻击。',
  },
  'mummy': {
    'name': '木乃伊',
    'description': '被对手接触到后，会将对手变为木乃伊。',
  },
  'moxie': {
    'name': '自信过度',
    'description': '如果打倒对手，就会充满自信，攻击会提高。',
  },
  'justified': {
    'name': '正义之心',
    'description': '受到恶属性的招式攻击时，因为正义感，攻击会提高。',
  },
  'rattled': {
    'name': '胆怯',
    'description': '受到恶属性、幽灵属性和虫属性的攻击或威吓时，会因胆怯而速度提高。',
  },
  'magic-bounce': {
    'name': '魔法镜',
    'description': '可以不受到由对手使出的变化招式影响，并将其反弹。',
  },
  'sap-sipper': {
    'name': '食草',
    'description': '受到草属性的招式攻击时，不会受到伤害，而是攻击会提高。',
  },
  'prankster': {
    'name': '恶作剧之心',
    'description': '可以率先使出变化招式。',
  },
  'sand-force': {
    'name': '沙之力',
    'description': '沙暴天气时，岩石属性、地面属性和钢属性的招式威力会提高。',
  },
  'iron-barbs': {
    'name': '铁刺',
    'description': '用铁刺给予接触到自己的对手伤害。',
  },
  'zen-mode': {
    'name': '达摩模式',
    'description': 'ＨＰ变为一半以下时，样子会改变。',
  },
  'victory-star': {
    'name': '胜利之星',
    'description': '自己和同伴的命中率会提高。',
  },
  'turboblaze': {
    'name': '涡轮火焰',
    'description': '可以不受对手特性的干扰，向对手使出招式。',
  },
  'teravolt': {
    'name': '兆级电压',
    'description': '可以不受对手特性的干扰，向对手使出招式。',
  },
  'aroma-veil': {
    'name': '芳香幕',
    'description': '可以防住向自己和同伴发出的心灵攻击。',
  },
  'flower-veil': {
    'name': '花幕',
    'description': '我方的草属性宝可梦能力不会降低，也不会变为异常状态。',
  },
  'cheek-pouch': {
    'name': '颊囊',
    'description': '无论是哪种树果，食用后，ＨＰ都会回复。',
  },
  'protean': {
    'name': '变幻自如',
    'description': '变为与自己使出的招式相同的属性。每次出场战斗仅生效一次。',
  },
  'fur-coat': {
    'name': '毛皮大衣',
    'description': '对手给予的物理招式的伤害会减半。',
  },
  'magician': {
    'name': '魔术师',
    'description': '夺走被自己的招式击中的对手的道具。',
  },
  'bulletproof': {
    'name': '防弹',
    'description': '可以防住对手的球和弹类招式。',
  },
  'competitive': {
    'name': '好胜',
    'description': '如果被对手降低能力，特攻会大幅提高。',
  },
  'strong-jaw': {
    'name': '强壮之颚',
    'description': '因为颚部强壮，啃咬类招式的威力会提高。',
  },
  'refrigerate': {
    'name': '冰冻皮肤',
    'description': '一般属性的招式会变为冰属性。威力会少量提高。',
  },
  'sweet-veil': {
    'name': '甜幕',
    'description': '自己和同伴的宝可梦不会变为睡眠状态。',
  },
  'stance-change': {
    'name': '战斗切换',
    'description': '如果使出攻击招式，会变为刀剑形态，如果使出招式“王者盾牌”，会变为盾牌形态。',
  },
  'gale-wings': {
    'name': '疾风之翼',
    'description': 'ＨＰ全满时，飞行属性的招式可以率先使出。',
  },
  'mega-launcher': {
    'name': '超级发射器',
    'description': '波动和波导类招式的威力会提高。',
  },
  'grass-pelt': {
    'name': '草之毛皮',
    'description': '在青草场地时，防御会提高。',
  },
  'symbiosis': {
    'name': '共生',
    'description': '同伴使用道具时，会把自己持有的道具传递给同伴。',
  },
  'tough-claws': {
    'name': '硬爪',
    'description': '接触到对手的招式威力会提高。',
  },
  'pixilate': {
    'name': '妖精皮肤',
    'description': '一般属性的招式会变为妖精属性。威力会少量提高。',
  },
  'gooey': {
    'name': '黏滑',
    'description': '对于用攻击接触到自己的对手，会降低其速度。',
  },
  'aerilate': {
    'name': '飞行皮肤',
    'description': '一般属性的招式会变为飞行属性。威力会少量提高。',
  },
  'parental-bond': {
    'name': '亲子爱',
    'description': '亲子俩可以合计攻击２次。',
  },
  'dark-aura': {
    'name': '暗黑气场',
    'description': '全体的恶属性招式变强。',
  },
  'fairy-aura': {
    'name': '妖精气场',
    'description': '全体的妖精属性招式变强。',
  },
  'aura-break': {
    'name': '气场破坏',
    'description': '让气场的效果发生逆转，降低威力。',
  },
  'primordial-sea': {
    'name': '始源之海',
    'description': '变为不会受到火属性攻击的天气。',
  },
  'desolate-land': {
    'name': '终结之地',
    'description': '变为不会受到水属性攻击的天气。',
  },
  'delta-stream': {
    'name': '德尔塔气流',
    'description': '变为令飞行属性的弱点消失的天气。',
  },
  'stamina': {
    'name': '持久力',
    'description': '受到攻击时，防御会提高。',
  },
  'wimp-out': {
    'name': '跃跃欲逃',
    'description': 'ＨＰ变为一半时，会慌慌张张逃走，退回同行队伍中。',
  },
  'emergency-exit': {
    'name': '危险回避',
    'description': 'ＨＰ变为一半时，为了回避危险，会退回到同行队伍中。',
  },
  'water-compaction': {
    'name': '遇水凝固',
    'description': '受到水属性的招式攻击时，防御会大幅提高。',
  },
  'merciless': {
    'name': '不仁不义',
    'description': '攻击中毒状态的对手时，必定会击中要害。',
  },
  'shields-down': {
    'name': '界限盾壳',
    'description': 'ＨＰ变为一半时，壳会坏掉，变得有攻击性。',
  },
  'stakeout': {
    'name': '蹲守',
    'description': '可以对替换出场的对手以２倍的伤害进行攻击。',
  },
  'water-bubble': {
    'name': '水泡',
    'description': '降低自己受到的火属性招式的威力，不会灼伤。',
  },
  'steelworker': {
    'name': '钢能力者',
    'description': '钢属性的招式威力会提高。',
  },
  'berserk': {
    'name': '怒火冲天',
    'description': '因对手的攻击ＨＰ变为一半时，特攻会提高。',
  },
  'slush-rush': {
    'name': '拨雪',
    'description': '下雪天气时，速度会提高。',
  },
  'long-reach': {
    'name': '远隔',
    'description': '可以不接触对手就使出所有的招式。',
  },
  'liquid-voice': {
    'name': '湿润之声',
    'description': '所有的声音招式都变为水属性。',
  },
  'triage': {
    'name': '先行治疗',
    'description': '可以率先使出回复招式。',
  },
  'galvanize': {
    'name': '电气皮肤',
    'description': '一般属性的招式会变为电属性。威力会少量提高。',
  },
  'surge-surfer': {
    'name': '冲浪之尾',
    'description': '电气场地时，速度会变为２倍。',
  },
  'schooling': {
    'name': '鱼群',
    'description': 'ＨＰ多的时候会聚起来变强。ＨＰ剩余量变少时，群体会分崩离析。',
  },
  'disguise': {
    'name': '画皮',
    'description': '通过画皮覆盖住身体，可以防住１次攻击。',
  },
  'battle-bond': {
    'name': '牵绊变身',
    'description': '打倒对手时，与训练家的牵绊会增强，自己的攻击、特攻、速度会提高。',
  },
  'power-construct': {
    'name': '群聚变形',
    'description': 'ＨＰ变为一半时，细胞们会赶来支援，变为完全体形态。',
  },
  'corrosion': {
    'name': '腐蚀',
    'description': '可以使钢属性和毒属性的宝可梦也陷入中毒状态。',
  },
  'comatose': {
    'name': '绝对睡眠',
    'description': '总是半梦半醒的状态，绝对不会醒来。可以就这么睡着进行攻击。',
  },
  'queenly-majesty': {
    'name': '女王的威严',
    'description': '向对手施加威慑力，使其无法对我方使出先制招式。',
  },
  'innards-out': {
    'name': '飞出的内在物',
    'description': '被对手打倒的时候，会给予对手相当于ＨＰ剩余量的伤害。',
  },
  'dancer': {
    'name': '舞者',
    'description': '有谁使出跳舞招式时，自己也能就这么接着使出跳舞招式。',
  },
  'battery': {
    'name': '蓄电池',
    'description': '会提高我方的特殊招式的威力。',
  },
  'fluffy': {
    'name': '毛茸茸',
    'description': '会将对手所给予的接触类招式的伤害减半，但火属性招式的伤害会变为２倍。',
  },
  'dazzling': {
    'name': '鲜艳之躯',
    'description': '让对手吓一跳，使其无法对我方使出先制招式。',
  },
  'soul-heart': {
    'name': '魂心',
    'description': '宝可梦每次变为濒死状态时，特攻会提高。',
  },
  'tangling-hair': {
    'name': '卷发',
    'description': '对于用攻击接触到自己的对手，会降低其速度。',
  },
  'receiver': {
    'name': '接球手',
    'description': '继承被打倒的同伴的特性，变为相同的特性。',
  },
  'power-of-alchemy': {
    'name': '化学之力',
    'description': '继承被打倒的同伴的特性，变为相同的特性。',
  },
  'beast-boost': {
    'name': '异兽提升',
    'description': '打倒对手的时候，自己最高的那项能力会提高。',
  },
  'rks-system': {
    'name': 'ＡＲ系统',
    'description': '根据持有的存储碟，自己的属性会改变。',
  },
  'electric-surge': {
    'name': '电气制造者',
    'description': '出场时，会布下电气场地。',
  },
  'psychic-surge': {
    'name': '精神制造者',
    'description': '出场时，会布下精神场地。',
  },
  'misty-surge': {
    'name': '薄雾制造者',
    'description': '出场时，会布下薄雾场地。',
  },
  'grassy-surge': {
    'name': '青草制造者',
    'description': '出场时，会布下青草场地。',
  },
  'full-metal-body': {
    'name': '金属防护',
    'description': '不会因为对手的招式或特性而被降低能力。',
  },
  'shadow-shield': {
    'name': '幻影防守',
    'description': 'ＨＰ全满时，受到的伤害会变少。',
  },
  'prism-armor': {
    'name': '棱镜装甲',
    'description': '受到效果绝佳的攻击时，可以减弱其威力。',
  },
  'neuroforce': {
    'name': '脑核之力',
    'description': '效果绝佳的攻击，威力会变得更强。',
  },
  'intrepid-sword': {
    'name': '不挠之剑',
    'description': '首次出场时，攻击会提高。',
  },
  'dauntless-shield': {
    'name': '不屈之盾',
    'description': '首次出场时，防御会提高。',
  },
  'libero': {
    'name': '自由者',
    'description': '变为与自己使出的招式相同的属性。每次出场战斗仅生效一次。',
  },
  'ball-fetch': {
    'name': '捡球',
    'description': '没有携带道具时，会拾取第１个投出后捕捉失败的精灵球。',
  },
  'cotton-down': {
    'name': '棉絮',
    'description': '受到攻击后撒下棉絮，降低除自己以外的所有宝可梦的速度。',
  },
  'propeller-tail': {
    'name': '螺旋尾鳍',
    'description': '能无视具有吸引对手招式效果的特性或招式的影响。',
  },
  'mirror-armor': {
    'name': '镜甲',
    'description': '只反弹自己受到的能力降低效果。',
  },
  'gulp-missile': {
    'name': '一口导弹',
    'description': '冲浪或潜水时会叼来猎物。受到伤害时，会吐出猎物进行攻击。',
  },
  'stalwart': {
    'name': '坚毅',
    'description': '能无视具有吸引对手招式效果的特性或招式的影响。',
  },
  'steam-engine': {
    'name': '蒸汽机',
    'description': '受到水属性或火属性的招式攻击时，速度会巨幅提高。',
  },
  'punk-rock': {
    'name': '庞克摇滚',
    'description': '声音招式的威力会提高。受到的声音招式伤害会减半。',
  },
  'sand-spit': {
    'name': '吐沙',
    'description': '受到攻击时，会刮起沙暴。',
  },
  'ice-scales': {
    'name': '冰鳞粉',
    'description': '由于有冰鳞粉的守护，受到的特殊攻击伤害会减半。',
  },
  'ripen': {
    'name': '熟成',
    'description': '使树果成熟，效果变为２倍。',
  },
  'ice-face': {
    'name': '结冻头',
    'description': '头部的冰会代替自己承受物理攻击，但是样子会改变。下雪时，冰会恢复原状。',
  },
  'power-spot': {
    'name': '能量点',
    'description': '只要处在相邻位置，招式的威力就会提高。',
  },
  'mimicry': {
    'name': '拟态',
    'description': '宝可梦的属性会根据场地的状态而变化。',
  },
  'screen-cleaner': {
    'name': '除障',
    'description': '出场时，敌方和我方的光墙、反射壁和极光幕的效果会消失。',
  },
  'steely-spirit': {
    'name': '钢之意志',
    'description': '我方的钢属性攻击威力会提高。',
  },
  'perish-body': {
    'name': '灭亡之躯',
    'description': '受到接触类招式攻击时，双方都会在３回合后变为濒死状态。替换后效果消失。',
  },
  'wandering-spirit': {
    'name': '游魂',
    'description': '与使用接触类招式攻击自己的宝可梦互换特性。',
  },
  'gorilla-tactics': {
    'name': '一猩一意',
    'description': '虽然攻击会提高，但是只能使出一开始所选的招式。',
  },
  'neutralizing-gas': {
    'name': '化学变化气体',
    'description': '特性为化学变化气体的宝可梦在场时，场上所有宝可梦的特性效果都会消失或者无法生效。',
  },
  'pastel-veil': {
    'name': '粉彩护幕',
    'description': '自己和同伴都不会陷入中毒的异常状态。',
  },
  'hunger-switch': {
    'name': '饱了又饿',
    'description': '每回合结束时会在满腹花纹与空腹花纹之间交替改变样子。',
  },
  'quick-draw': {
    'name': '速击',
    'description': '有时能比对手先一步行动。',
  },
  'unseen-fist': {
    'name': '无形拳',
    'description': '如果使出的是接触到对手的招式，就可以无视守护效果进行攻击。',
  },
  'curious-medicine': {
    'name': '怪药',
    'description': '出场时会从贝壳撒药，将我方的能力变化复原。',
  },
  'transistor': {
    'name': '电晶体',
    'description': '电属性的招式威力会提高。',
  },
  'dragon\'s-maw': {
    'name': '龙颚',
    'description': '龙属性的招式威力会提高。',
  },
  'chilling-neigh': {
    'name': '苍白嘶鸣',
    'description': '打倒对手时会用冰冷的声音嘶鸣并提高攻击。',
  },
  'grim-neigh': {
    'name': '漆黑嘶鸣',
    'description': '打倒对手时会用恐怖的声音嘶鸣并提高特攻。',
  },
  'as-one': {
    'name': '人马一体',
    'description': '兼备蕾冠王的紧张感和雪暴马的苍白嘶鸣这两种特性。',
  },
  'lingering-aroma': {
    'name': '甩不掉的气味',
    'description': '被对手接触到后，甩不掉的气味会沾上对手。',
  },
  'seed-sower': {
    'name': '掉出种子',
    'description': '受到攻击时，会将脚下变成青草场地。',
  },
  'thermal-exchange': {
    'name': '热交换',
    'description': '受到火属性的招式攻击时，攻击会提高，且不会陷入灼伤状态。',
  },
  'anger-shell': {
    'name': '愤怒甲壳',
    'description': '因被对手攻击而ＨＰ变为一半时，会因愤怒降低防御和特防。但攻击、特攻、速度会提高。',
  },
  'purifying-salt': {
    'name': '洁净之盐',
    'description': '因洁净的盐而不会陷入异常状态。会让幽灵属性的招式伤害减半。',
  },
  'well-baked-body': {
    'name': '焦香之躯',
    'description': '受到火属性的招式攻击时，不会受到伤害，而是会大幅提高防御。',
  },
  'wind-rider': {
    'name': '乘风',
    'description': '吹起了顺风或受到风的招式攻击时，不会受到伤害，而是会提高攻击。',
  },
  'guard-dog': {
    'name': '看门犬',
    'description': '受到威吓时，攻击会提高。让替换宝可梦的招式和道具无效。',
  },
  'rocky-payload': {
    'name': '搬岩',
    'description': '岩石属性的招式威力会提高。',
  },
  'wind-power': {
    'name': '风力发电',
    'description': '受到风的招式攻击时，会变为充电状态。',
  },
  'zero-to-hero': {
    'name': '全能变身',
    'description': '回到同行队伍后，会变为全能形态。',
  },
  'commander': {
    'name': '发号施令',
    'description': '出场时，若我方当中有吃吼霸，就会进入其口中，并从其口中发出指令。',
  },
  'electromorphosis': {
    'name': '电力转换',
    'description': '受到伤害时，会变为充电状态。',
  },
  'protosynthesis': {
    'name': '古代活性',
    'description': '携带着驱劲能量或天气为晴朗时，数值最高的能力会提高。',
  },
  'quark-drive': {
    'name': '夸克充能',
    'description': '携带着驱劲能量或在电气场地上时，数值最高的能力会提高。',
  },
  'good-as-gold': {
    'name': '黄金之躯',
    'description': '不会氧化的坚固黄金身躯不会受到对手的变化招式的影响。',
  },
  'vessel-of-ruin': {
    'name': '灾祸之鼎',
    'description': '以能呼唤灾厄的鼎的力量降低除自己以外的宝可梦的特攻。',
  },
  'sword-of-ruin': {
    'name': '灾祸之剑',
    'description': '以能呼唤灾厄的剑的力量降低除自己以外的宝可梦的防御。',
  },
  'tablets-of-ruin': {
    'name': '灾祸之简',
    'description': '以能呼唤灾厄的简的力量降低除自己以外的宝可梦的攻击。',
  },
  'beads-of-ruin': {
    'name': '灾祸之玉',
    'description': '以能呼唤灾厄的勾玉的力量降低除自己以外的宝可梦的特防。',
  },
  'orichalcum-pulse': {
    'name': '绯红脉动',
    'description': '出场时，会将天气变为晴朗。日照强烈时，会通过古代的脉动升高攻击。',
  },
  'hadron-engine': {
    'name': '强子引擎',
    'description': '出场时，会布下电气场地。处于电气场地时，会通过未来的机关升高特攻。',
  },
  'opportunist': {
    'name': '跟风',
    'description': '对手的能力提高时，自己也会趁机同样地提高能力。',
  },
  'cud-chew': {
    'name': '反刍',
    'description': '吃了树果后，会在下一回合结束时从胃反刍出来再吃１次。',
  },
  'sharpness': {
    'name': '锋锐',
    'description': '提高切割对手的招式的威力。',
  },
  'supreme-overlord': {
    'name': '大将',
    'description': '出场时，攻击和特攻会按照目前被打倒的同伴数量逐渐提升，被打倒越多，提升越多。',
  },
  'costar': {
    'name': '同台共演',
    'description': '出场时，复制同伴的能力变化。',
  },
  'toxic-debris': {
    'name': '毒满地',
    'description': '受到物理招式的伤害时，会在对手脚下散布毒菱。',
  },
  'armor-tail': {
    'name': '尾甲',
    'description': '包裹头部的神秘尾巴使对手无法对我方使出先制招式。',
  },
  'earth-eater': {
    'name': '食土',
    'description': '受到地面属性的招式攻击时，不会受到伤害，而是会得到回复。',
  },
  'mycelium-might': {
    'name': '菌丝之力',
    'description': '使出变化招式时，虽然行动必定会变慢，但能不受对手的特性妨碍。',
  },
  'hospitality': {
    'name': '款待',
    'description': '出场时款待同伴，回复其少量ＨＰ。',
  },
  'mind\'s-eye': {
    'name': '心眼',
    'description': '一般属性和格斗属性的招式可以击中幽灵属性的宝可梦。无视对手的闪避率的变化，且命中率不会被降低。',
  },
  'embody-aspect': {
    'name': '面影辉映',
    'description': '将回忆映于心中，让碧草面具发出光辉，提高自己的速度。',
  },
  'toxic-chain': {
    'name': '毒锁链',
    'description': '凭借含有毒素的锁链的力量，有时能让被招式击中的对手陷入剧毒状态。',
  },
  'supersweet-syrup': {
    'name': '甘露之蜜',
    'description': '首次出场时，会散发出甜腻的蜜的香味来降低对手的闪避率。',
  },
  'tera-shift': {
    'name': '太晶变形',
    'description': '出场时，会吸收周围的能量，变为太晶形态。',
  },
  'tera-shell': {
    'name': '太晶甲壳',
    'description': '甲壳蕴藏着全部属性的力量，会将自己ＨＰ全满时受到的伤害全都变为效果不好。',
  },
  'teraform-zero': {
    'name': '归零化境',
    'description': '太乐巴戈斯变为星晶形态时，蕴藏在它身上的力量会将天气和场地的影响全部归零。',
  },
  'poison-puppeteer': {
    'name': '毒傀儡',
    'description': '因桃歹郎的招式而陷入中毒状态的对手同时也会陷入混乱状态。',
  },
};

const Map<String, String> abilityNameTranslations = {
  'Stench': '恶臭',
  'Drizzle': '降雨',
  'Speed Boost': '加速',
  'Battle Armor': '战斗盔甲',
  'Sturdy': '结实',
  'Damp': '湿气',
  'Limber': '柔软',
  'Sand Veil': '沙隐',
  'Static': '静电',
  'Volt Absorb': '蓄电',
  'Water Absorb': '储水',
  'Oblivious': '迟钝',
  'Cloud Nine': '无关天气',
  'Compound Eyes': '复眼',
  'Insomnia': '不眠',
  'Color Change': '变色',
  'Immunity': '免疫',
  'Flash Fire': '引火',
  'Shield Dust': '鳞粉',
  'Own Tempo': '我行我素',
  'Suction Cups': '吸盘',
  'Intimidate': '威吓',
  'Shadow Tag': '踩影',
  'Rough Skin': '粗糙皮肤',
  'Wonder Guard': '神奇守护',
  'Levitate': '飘浮',
  'Effect Spore': '孢子',
  'Synchronize': '同步',
  'Clear Body': '恒净之躯',
  'Natural Cure': '自然回复',
  'Lightning Rod': '避雷针',
  'Serene Grace': '天恩',
  'Swift Swim': '悠游自如',
  'Chlorophyll': '叶绿素',
  'Illuminate': '发光',
  'Trace': '复制',
  'Huge Power': '大力士',
  'Poison Point': '毒刺',
  'Inner Focus': '精神力',
  'Magma Armor': '熔岩铠甲',
  'Water Veil': '水幕',
  'Magnet Pull': '磁力',
  'Soundproof': '隔音',
  'Rain Dish': '雨盘',
  'Sand Stream': '扬沙',
  'Pressure': '压迫感',
  'Thick Fat': '厚脂肪',
  'Early Bird': '早起',
  'Flame Body': '火焰之躯',
  'Run Away': '逃跑',
  'Keen Eye': '锐利目光',
  'Hyper Cutter': '怪力钳',
  'Pickup': '捡拾',
  'Truant': '懒惰',
  'Hustle': '活力',
  'Cute Charm': '迷人之躯',
  'Plus': '正电',
  'Minus': '负电',
  'Forecast': '阴晴不定',
  'Sticky Hold': '黏着',
  'Shed Skin': '蜕皮',
  'Guts': '毅力',
  'Marvel Scale': '神奇鳞片',
  'Liquid Ooze': '污泥浆',
  'Overgrow': '茂盛',
  'Blaze': '猛火',
  'Torrent': '激流',
  'Swarm': '虫之预感',
  'Rock Head': '坚硬脑袋',
  'Drought': '日照',
  'Arena Trap': '沙穴',
  'Vital Spirit': '干劲',
  'White Smoke': '白色烟雾',
  'Pure Power': '瑜伽之力',
  'Shell Armor': '硬壳盔甲',
  'Cacophony': '杂音',
  'Air Lock': '气闸',
  'Tangled Feet': '蹒跚',
  'Motor Drive': '电气引擎',
  'Rivalry': '斗争心',
  'Steadfast': '不屈之心',
  'Snow Cloak': '雪隐',
  'Gluttony': '贪吃鬼',
  'Anger Point': '愤怒穴位',
  'Unburden': '轻装',
  'Heatproof': '耐热',
  'Simple': '单纯',
  'Dry Skin': '干燥皮肤',
  'Download': '下载',
  'Iron Fist': '铁拳',
  'Poison Heal': '毒疗',
  'Adaptability': '适应力',
  'Skill Link': '连续攻击',
  'Hydration': '湿润之躯',
  'Solar Power': '太阳之力',
  'Quick Feet': '飞毛腿',
  'Normalize': '一般皮肤',
  'Sniper': '狙击手',
  'Magic Guard': '魔法防守',
  'No Guard': '无防守',
  'Stall': '慢出',
  'Technician': '技术高手',
  'Leaf Guard': '叶子防守',
  'Klutz': '笨拙',
  'Mold Breaker': '破格',
  'Super Luck': '超幸运',
  'Aftermath': '引爆',
  'Anticipation': '危险预知',
  'Forewarn': '预知梦',
  'Unaware': '纯朴',
  'Tinted Lens': '有色眼镜',
  'Filter': '过滤',
  'Slow Start': '慢启动',
  'Scrappy': '胆量',
  'Storm Drain': '引水',
  'Ice Body': '冰冻之躯',
  'Solid Rock': '坚硬岩石',
  'Snow Warning': '降雪',
  'Honey Gather': '采蜜',
  'Frisk': '察觉',
  'Reckless': '舍身',
  'Multitype': '多属性',
  'Flower Gift': '花之礼',
  'Bad Dreams': '梦魇',
  'Pickpocket': '顺手牵羊',
  'Sheer Force': '强行',
  'Contrary': '唱反调',
  'Unnerve': '紧张感',
  'Defiant': '不服输',
  'Defeatist': '软弱',
  'Cursed Body': '咒术之躯',
  'Healer': '治愈之心',
  'Friend Guard': '友情防守',
  'Weak Armor': '碎裂铠甲',
  'Heavy Metal': '重金属',
  'Light Metal': '轻金属',
  'Multiscale': '多重鳞片',
  'Toxic Boost': '中毒激升',
  'Flare Boost': '受热激升',
  'Harvest': '收获',
  'Telepathy': '心灵感应',
  'Moody': '心情不定',
  'Overcoat': '防尘',
  'Poison Touch': '毒手',
  'Regenerator': '再生力',
  'Big Pecks': '健壮胸肌',
  'Sand Rush': '拨沙',
  'Wonder Skin': '奇迹皮肤',
  'Analytic': '分析',
  'Illusion': '幻觉',
  'Imposter': '变身者',
  'Infiltrator': '穿透',
  'Mummy': '木乃伊',
  'Moxie': '自信过度',
  'Justified': '正义之心',
  'Rattled': '胆怯',
  'Magic Bounce': '魔法镜',
  'Sap Sipper': '食草',
  'Prankster': '恶作剧之心',
  'Sand Force': '沙之力',
  'Iron Barbs': '铁刺',
  'Zen Mode': '达摩模式',
  'Victory Star': '胜利之星',
  'Turboblaze': '涡轮火焰',
  'Teravolt': '兆级电压',
  'Aroma Veil': '芳香幕',
  'Flower Veil': '花幕',
  'Cheek Pouch': '颊囊',
  'Protean': '变幻自如',
  'Fur Coat': '毛皮大衣',
  'Magician': '魔术师',
  'Bulletproof': '防弹',
  'Competitive': '好胜',
  'Strong Jaw': '强壮之颚',
  'Refrigerate': '冰冻皮肤',
  'Sweet Veil': '甜幕',
  'Stance Change': '战斗切换',
  'Gale Wings': '疾风之翼',
  'Mega Launcher': '超级发射器',
  'Grass Pelt': '草之毛皮',
  'Symbiosis': '共生',
  'Tough Claws': '硬爪',
  'Pixilate': '妖精皮肤',
  'Gooey': '黏滑',
  'Aerilate': '飞行皮肤',
  'Parental Bond': '亲子爱',
  'Dark Aura': '暗黑气场',
  'Fairy Aura': '妖精气场',
  'Aura Break': '气场破坏',
  'Primordial Sea': '始源之海',
  'Desolate Land': '终结之地',
  'Delta Stream': '德尔塔气流',
  'Stamina': '持久力',
  'Wimp Out': '跃跃欲逃',
  'Emergency Exit': '危险回避',
  'Water Compaction': '遇水凝固',
  'Merciless': '不仁不义',
  'Shields Down': '界限盾壳',
  'Stakeout': '蹲守',
  'Water Bubble': '水泡',
  'Steelworker': '钢能力者',
  'Berserk': '怒火冲天',
  'Slush Rush': '拨雪',
  'Long Reach': '远隔',
  'Liquid Voice': '湿润之声',
  'Triage': '先行治疗',
  'Galvanize': '电气皮肤',
  'Surge Surfer': '冲浪之尾',
  'Schooling': '鱼群',
  'Disguise': '画皮',
  'Battle Bond': '牵绊变身',
  'Power Construct': '群聚变形',
  'Corrosion': '腐蚀',
  'Comatose': '绝对睡眠',
  'Queenly Majesty': '女王的威严',
  'Innards Out': '飞出的内在物',
  'Dancer': '舞者',
  'Battery': '蓄电池',
  'Fluffy': '毛茸茸',
  'Dazzling': '鲜艳之躯',
  'Soul-Heart': '魂心',
  'Tangling Hair': '卷发',
  'Receiver': '接球手',
  'Power of Alchemy': '化学之力',
  'Beast Boost': '异兽提升',
  'RKS System': 'ＡＲ系统',
  'Electric Surge': '电气制造者',
  'Psychic Surge': '精神制造者',
  'Misty Surge': '薄雾制造者',
  'Grassy Surge': '青草制造者',
  'Full Metal Body': '金属防护',
  'Shadow Shield': '幻影防守',
  'Prism Armor': '棱镜装甲',
  'Neuroforce': '脑核之力',
  'Intrepid Sword': '不挠之剑',
  'Dauntless Shield': '不屈之盾',
  'Libero': '自由者',
  'Ball Fetch': '捡球',
  'Cotton Down': '棉絮',
  'Propeller Tail': '螺旋尾鳍',
  'Mirror Armor': '镜甲',
  'Gulp Missile': '一口导弹',
  'Stalwart': '坚毅',
  'Steam Engine': '蒸汽机',
  'Punk Rock': '庞克摇滚',
  'Sand Spit': '吐沙',
  'Ice Scales': '冰鳞粉',
  'Ripen': '熟成',
  'Ice Face': '结冻头',
  'Power Spot': '能量点',
  'Mimicry': '拟态',
  'Screen Cleaner': '除障',
  'Steely Spirit': '钢之意志',
  'Perish Body': '灭亡之躯',
  'Wandering Spirit': '游魂',
  'Gorilla Tactics': '一猩一意',
  'Neutralizing Gas': '化学变化气体',
  'Pastel Veil': '粉彩护幕',
  'Hunger Switch': '饱了又饿',
  'Quick Draw': '速击',
  'Unseen Fist': '无形拳',
  'Curious Medicine': '怪药',
  'Transistor': '电晶体',
  'Dragon\'s Maw': '龙颚',
  'Chilling Neigh': '苍白嘶鸣',
  'Grim Neigh': '漆黑嘶鸣',
  'As One': '人马一体',
  'Lingering Aroma': '甩不掉的气味',
  'Seed Sower': '掉出种子',
  'Thermal Exchange': '热交换',
  'Anger Shell': '愤怒甲壳',
  'Purifying Salt': '洁净之盐',
  'Well-Baked Body': '焦香之躯',
  'Wind Rider': '乘风',
  'Guard Dog': '看门犬',
  'Rocky Payload': '搬岩',
  'Wind Power': '风力发电',
  'Zero to Hero': '全能变身',
  'Commander': '发号施令',
  'Electromorphosis': '电力转换',
  'Protosynthesis': '古代活性',
  'Quark Drive': '夸克充能',
  'Good as Gold': '黄金之躯',
  'Vessel of Ruin': '灾祸之鼎',
  'Sword of Ruin': '灾祸之剑',
  'Tablets of Ruin': '灾祸之简',
  'Beads of Ruin': '灾祸之玉',
  'Orichalcum Pulse': '绯红脉动',
  'Hadron Engine': '强子引擎',
  'Opportunist': '跟风',
  'Cud Chew': '反刍',
  'Sharpness': '锋锐',
  'Supreme Overlord': '大将',
  'Costar': '同台共演',
  'Toxic Debris': '毒满地',
  'Armor Tail': '尾甲',
  'Earth Eater': '食土',
  'Mycelium Might': '菌丝之力',
  'Hospitality': '款待',
  'Mind\'s Eye': '心眼',
  'Embody Aspect': '面影辉映',
  'Toxic Chain': '毒锁链',
  'Supersweet Syrup': '甘露之蜜',
  'Tera Shift': '太晶变形',
  'Tera Shell': '太晶甲壳',
  'Teraform Zero': '归零化境',
  'Poison Puppeteer': '毒傀儡',
};

const Map<int, String> abilityIdToSlug = {
  1: 'stench',
  2: 'drizzle',
  3: 'speed-boost',
  4: 'battle-armor',
  5: 'sturdy',
  6: 'damp',
  7: 'limber',
  8: 'sand-veil',
  9: 'static',
  10: 'volt-absorb',
  11: 'water-absorb',
  12: 'oblivious',
  13: 'cloud-nine',
  14: 'compound-eyes',
  15: 'insomnia',
  16: 'color-change',
  17: 'immunity',
  18: 'flash-fire',
  19: 'shield-dust',
  20: 'own-tempo',
  21: 'suction-cups',
  22: 'intimidate',
  23: 'shadow-tag',
  24: 'rough-skin',
  25: 'wonder-guard',
  26: 'levitate',
  27: 'effect-spore',
  28: 'synchronize',
  29: 'clear-body',
  30: 'natural-cure',
  31: 'lightning-rod',
  32: 'serene-grace',
  33: 'swift-swim',
  34: 'chlorophyll',
  35: 'illuminate',
  36: 'trace',
  37: 'huge-power',
  38: 'poison-point',
  39: 'inner-focus',
  40: 'magma-armor',
  41: 'water-veil',
  42: 'magnet-pull',
  43: 'soundproof',
  44: 'rain-dish',
  45: 'sand-stream',
  46: 'pressure',
  47: 'thick-fat',
  48: 'early-bird',
  49: 'flame-body',
  50: 'run-away',
  51: 'keen-eye',
  52: 'hyper-cutter',
  53: 'pickup',
  54: 'truant',
  55: 'hustle',
  56: 'cute-charm',
  57: 'plus',
  58: 'minus',
  59: 'forecast',
  60: 'sticky-hold',
  61: 'shed-skin',
  62: 'guts',
  63: 'marvel-scale',
  64: 'liquid-ooze',
  65: 'overgrow',
  66: 'blaze',
  67: 'torrent',
  68: 'swarm',
  69: 'rock-head',
  70: 'drought',
  71: 'arena-trap',
  72: 'vital-spirit',
  73: 'white-smoke',
  74: 'pure-power',
  75: 'shell-armor',
  76: 'cacophony',
  77: 'tangled-feet',
  78: 'motor-drive',
  79: 'rivalry',
  80: 'steadfast',
  81: 'snow-cloak',
  82: 'gluttony',
  83: 'anger-point',
  84: 'unburden',
  85: 'heatproof',
  86: 'simple',
  87: 'dry-skin',
  88: 'download',
  89: 'iron-fist',
  90: 'poison-heal',
  91: 'adaptability',
  92: 'skill-link',
  93: 'hydration',
  94: 'solar-power',
  95: 'quick-feet',
  96: 'normalize',
  97: 'sniper',
  98: 'magic-guard',
  99: 'no-guard',
  100: 'stall',
  101: 'technician',
  102: 'leaf-guard',
  103: 'klutz',
  104: 'mold-breaker',
  105: 'super-luck',
  106: 'aftermath',
  107: 'anticipation',
  108: 'forewarn',
  109: 'unaware',
  110: 'tinted-lens',
  111: 'filter',
  112: 'slow-start',
  113: 'scrappy',
  114: 'storm-drain',
  115: 'ice-body',
  116: 'solid-rock',
  117: 'snow-warning',
  118: 'honey-gather',
  119: 'frisk',
  120: 'reckless',
  121: 'multitype',
  122: 'flower-gift',
  123: 'bad-dreams',
  124: 'pickpocket',
  125: 'sheer-force',
  126: 'contrary',
  127: 'unnerve',
  128: 'defiant',
  129: 'defeatist',
  130: 'cursed-body',
  131: 'healer',
  132: 'friend-guard',
  133: 'weak-armor',
  134: 'heavy-metal',
  135: 'light-metal',
  136: 'multiscale',
  137: 'toxic-boost',
  138: 'flare-boost',
  139: 'harvest',
  140: 'telepathy',
  141: 'moody',
  142: 'overcoat',
  143: 'poison-touch',
  144: 'regenerator',
  145: 'big-pecks',
  146: 'sand-rush',
  147: 'wonder-skin',
  148: 'analytic',
  149: 'illusion',
  150: 'imposter',
  151: 'infiltrator',
  152: 'mummy',
  153: 'moxie',
  154: 'justified',
  155: 'rattled',
  156: 'magic-bounce',
  157: 'sap-sipper',
  158: 'prankster',
  159: 'sand-force',
  160: 'iron-barbs',
  161: 'zen-mode',
  162: 'victory-star',
  163: 'turboblaze',
  164: 'teravolt',
  165: 'aroma-veil',
  166: 'flower-veil',
  167: 'cheek-pouch',
  168: 'protean',
  169: 'fur-coat',
  170: 'magician',
  171: 'bulletproof',
  172: 'competitive',
  173: 'strong-jaw',
  174: 'refrigerate',
  175: 'sweet-veil',
  176: 'stance-change',
  177: 'gale-wings',
  178: 'mega-launcher',
  179: 'grass-pelt',
  180: 'symbiosis',
  181: 'tough-claws',
  182: 'pixilate',
  183: 'gooey',
  184: 'aerilate',
  185: 'parental-bond',
  186: 'dark-aura',
  187: 'fairy-aura',
  188: 'aura-break',
  189: 'primordial-sea',
  190: 'desolate-land',
  191: 'delta-stream',
  192: 'stamina',
  193: 'wimp-out',
  194: 'emergency-exit',
  195: 'water-compaction',
  196: 'merciless',
  197: 'shields-down',
  198: 'stakeout',
  199: 'water-bubble',
  200: 'steelworker',
  201: 'berserk',
  202: 'slush-rush',
  203: 'long-reach',
  204: 'liquid-voice',
  205: 'triage',
  206: 'galvanize',
  207: 'surge-surfer',
  208: 'schooling',
  209: 'disguise',
  210: 'battle-bond',
  211: 'power-construct',
  212: 'corrosion',
  213: 'comatose',
  214: 'queenly-majesty',
  215: 'innards-out',
  216: 'dancer',
  217: 'battery',
  218: 'fluffy',
  219: 'dazzling',
  220: 'soul-heart',
  221: 'tangling-hair',
  222: 'receiver',
  223: 'power-of-alchemy',
  224: 'beast-boost',
  225: 'rks-system',
  226: 'electric-surge',
  227: 'psychic-surge',
  228: 'misty-surge',
  229: 'grassy-surge',
  230: 'full-metal-body',
  231: 'shadow-shield',
  232: 'prism-armor',
  233: 'neuroforce',
  234: 'intrepid-sword',
  235: 'dauntless-shield',
  236: 'libero',
  237: 'ball-fetch',
  238: 'cotton-down',
  239: 'propeller-tail',
  240: 'mirror-armor',
  241: 'gulp-missile',
  242: 'stalwart',
  243: 'steam-engine',
  244: 'punk-rock',
  245: 'sand-spit',
  246: 'ice-scales',
  247: 'ripen',
  248: 'ice-face',
  249: 'power-spot',
  250: 'mimicry',
  251: 'screen-cleaner',
  252: 'steely-spirit',
  253: 'perish-body',
  254: 'wandering-spirit',
  255: 'gorilla-tactics',
  256: 'neutralizing-gas',
  257: 'pastel-veil',
  258: 'hunger-switch',
  259: 'quick-draw',
  260: 'unseen-fist',
  261: 'curious-medicine',
  262: 'transistor',
  263: 'dragon\'s-maw',
  264: 'chilling-neigh',
  265: 'grim-neigh',
  266: 'as-one',
  267: 'as-one',
  268: 'lingering-aroma',
  269: 'seed-sower',
  270: 'thermal-exchange',
  271: 'anger-shell',
  272: 'purifying-salt',
  273: 'well-baked-body',
  274: 'wind-rider',
  275: 'guard-dog',
  276: 'rocky-payload',
  277: 'wind-power',
  278: 'zero-to-hero',
  279: 'commander',
  280: 'electromorphosis',
  281: 'protosynthesis',
  282: 'quark-drive',
  283: 'good-as-gold',
  284: 'vessel-of-ruin',
  285: 'sword-of-ruin',
  286: 'tablets-of-ruin',
  287: 'beads-of-ruin',
  288: 'orichalcum-pulse',
  289: 'hadron-engine',
  290: 'opportunist',
  291: 'cud-chew',
  292: 'sharpness',
  293: 'supreme-overlord',
  294: 'costar',
  295: 'toxic-debris',
  296: 'armor-tail',
  297: 'earth-eater',
  298: 'mycelium-might',
  299: 'hospitality',
  300: 'mind\'s-eye',
  301: 'embody-aspect',
  302: 'embody-aspect',
  303: 'embody-aspect',
  304: 'embody-aspect',
  305: 'toxic-chain',
  306: 'supersweet-syrup',
  307: 'tera-shift',
  308: 'tera-shell',
  309: 'teraform-zero',
  310: 'poison-puppeteer',
};
